# Generated by Django 3.0.5 on 2020-05-05 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djavError', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggedCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_name', models.CharField(max_length=200)),
                ('started', models.DateTimeField()),
                ('completed', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('error', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djavError.Error')),
            ],
            options={
                'ordering': ('-started',),
            },
        ),
    ]
